[package]
name = "retain"
version = "0.1.0-pre"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]


[dependencies]
clack-plugin = { path = "../clack/plugin" }
clack-extensions = { path = "../clack/extensions", features = [
    "audio-ports",
    "clack-plugin",
    "gui",
    "note-ports",
    "params",
    "raw-window-handle_05",
    "state",
	"latency",
] }
baseview = { git = "https://github.com/RustAudio/baseview.git", rev = "237d323c729f3aa99476ba3efa50129c5e86cad3", version = "0.1.0" }
egui-baseview = { git = "https://codeberg.org/BillyDM/egui-baseview.git", version = "0.7.0" }

# for calculation
realfft = { version = "3.5.0", features = ["avx", "neon", "sse"] }
num-complex = "0.4.6"
rustc-hash = "2.1.2"
atomic_float = "1.1.0"

# for saving the state
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
