[package]
name = "retain"
version = "0.1.0"
authors = [ "haemolacriaa" ]
description = "Retain is a real-time audio plugin that retains the nth largest magnitude frequencies in a signal"
edition = "2024"
repository = "https://git.haemolacriaa.com/retain"
license = "GPL-3.0"
publish = false

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
nice-plug = { path = "../nice-plug/crates/nice-plug", version = "0.1.0" }
nice-plug-egui = { path = "../nice-plug/crates/nice-plug-egui", version = "0.1.5" }
realfft = { version = "3.5.0", features = ["avx", "neon", "sse"] }
num-complex = "0.4.6"
rustc-hash = "2.1.2"
rtrb = "0.3.4"
egui = "0.34.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
